#pragma once

#include "magic_enum/core/check.hpp"
#include "magic_enum/core/core.hpp"
#include "magic_enum/core/enum_cast.hpp"
#include "magic_enum/core/enum_concept.hpp"
#include "magic_enum/core/enum_config.hpp"
#include "magic_enum/core/enum_contains.hpp"
#include "magic_enum/core/enum_count.hpp"
#include "magic_enum/core/enum_customize.hpp"
#include "magic_enum/core/enum_entries.hpp"
#include "magic_enum/core/enum_index.hpp"
#include "magic_enum/core/enum_integer.hpp"
#include "magic_enum/core/enum_name.hpp"
#include "magic_enum/core/enum_type_name.hpp"
#include "magic_enum/core/enum_value.hpp"
#include "magic_enum/core/version.hpp"
